import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/main-component/Header";
import Footer from "@/main-component/Footer";
import { StateProvider } from "@/context/StateContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SkillSphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StateProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </StateProvider>
      </body>
    </html>
  );
}